import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from "../components/Hero";
import Companies from "../components/Companies";
import Guide from "../components/Guide";
import Properties from "../components/Properties";
import Details from "../components/Details";
import GetStarted from "../components/GetStarted";
import Footer from "../components/Footer";

export default function Home() {
    return (
        <>
            <Head>
                <title>MicroFinance</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Hero/>
            <Companies/>
            <Guide/>
            <Properties/>
            <Details/>
            <GetStarted/>
            <Footer/>
        </>
    )
}
